name: tuk_gen
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^1.1.2
  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  progress_dialog: ^1.2.0
  shared_preferences: ^0.5.12+4
  google_maps_flutter: ^1.0.6
  flutter_google_places: ^0.2.8
  geolocator: ^6.1.13
  location: ^3.1.0
  geoflutterfire: ^2.2.2
  geocoder: ^0.2.1
  geocoding: ^1.0.5
  flutter_polyline_points: ^0.2.4
  lottie: ^0.7.0+1
  firebase_messaging: 8.0.0-dev.14
  modal_bottom_sheet: ^1.0.0+1
  flutter_rating_bar: ^3.2.0+1
  #image_picker: ^0.6.3
  firebase_storage: ^7.0.0
  intl: ^0.16.0

  #dependencias de login
  sign_button: ^1.0.2
  google_sign_in: ^4.5.1
  flutter_facebook_auth: ^2.0.2


  #dependencias propias del paquete tuk_gen
  package_info: ^0.4.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/img/
    - assets/json/
    - assets/gif/
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico/Pacifico.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf

    - family: RobotoMedium
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf

    - family: NimbusSans
      fonts:
        - asset: assets/fonts/NimbusSans/NimbusSanL-Reg.otf

    - family: OneDay
      fonts:
        - asset: assets/fonts/OneDay/ONEDAY.ttf

